StudyWeb/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Study.DataAccess.Repository.IRepository;
using Study.Models;

namespace StudyWeb.Controllers
{

    public class DashboardController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public DashboardController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ProductCategoryList()
        {
            IEnumerable<ProductCategory> objProductCategoryList = _unitOfWork.ProductCategory.GetAll();
            return View(objProductCategoryList);
        }
        public IActionResult ProductCategoryCreate()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ProductCategoryCreate(ProductCategory obj)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.ProductCategory.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Ürün kategorisi oluşturuldu";
                return RedirectToAction("ProductCategoryList");
            }
            return View(obj);
        }
        public IActionResult ProductCategoryDelete(int? id)
        {
            IEnumerable<ProductCategory> objProductCategoryList = _unitOfWork.ProductCategory.GetAll();
            return View(objProductCategoryList);
        }        
       // [HttpPost]
       // [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.ProductCategory.GetFirstOrDefault(u => u.Id == id);
            if(obj==null)
            {
                return NotFound();
            }
            _unitOfWork.ProductCategory.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Ürün Kategorisi Başarıyla Silindi";
            return RedirectToAction("ProductCategoryDelete");
        }

        //Get
        public IActionResult ProductCategoryUpdate()
        {
            IEnumerable<ProductCategory> objProductCategoryList = _unitOfWork.ProductCategory.GetAll();
            return View(objProductCategoryList);
        }
        public IActionResult ProductCategoryUpdated(int? id)
        {
            if (id==null || id==0)
            {
                return NotFound();
            }
            var ProductCategoryFromDbFirst = _unitOfWork.ProductCategory.GetFirstOrDefault(u => u.Id == id);
            if(ProductCategoryFromDbFirst==null)
            {
                return NotFound();
            }
            return View(ProductCategoryFromDbFirst);
        }
        //POST
        [HttpPost]
        public IActionResult ProductCategoryUpdated(ProductCategory obj)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.ProductCategory.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Ürün Kategorisi Düzenleme Başarılı";
                return RedirectToAction("ProductCategoryList");
            }
            return View(obj);
        }
        public IActionResult ProductCreate()
        {
            return View();
        }

    }
}

StudyWeb/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Study.DataAccess.Repository.IRepository;
using Study.Models.ViewModels;

namespace StudyWeb.Controllers;

public class ProductController : Controller
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly IWebHostEnvironment _hostEnvironment;
    public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment)
    {
        _unitOfWork = unitOfWork;
        _hostEnvironment = hostEnvironment;
    }
    public IActionResult Index()
    {
        return View();
    }
    //GET
    public IActionResult Upsert(int? id)
    {
        ProductVM productVM = new()
        {
            Product = new(),
            ProductCategoryList = _unitOfWork.ProductCategory.GetAll().Select(i => new SelectListItem
            {
                Text = i.Type,
                Value = i.Id.ToString()
            })
        };
        if (id == null || id == 0)
        {
            return View(productVM);
        }
        else
        {
            productVM.Product = _unitOfWork.Products.GetFirstOrDefault(u => u.Id == id);
            return View(productVM);
            //update product
        }
    }
    //POST
    [HttpPost]
    public IActionResult Upsert(ProductVM obj, IFormFile file)
    {
        if (ModelState.IsValid)
        {
            string wwwRoothPath = _hostEnvironment.WebRootPath;
            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(wwwRoothPath, @"images\products");
                if (obj.Product.ImageUrl != null)
                {
                    var oldImagePath = Path.Combine(wwwRoothPath, obj.Product.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }
                }
                var extension = Path.GetExtension(file.FileName);
                using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    file.CopyTo(fileStreams);
                }
                obj.Product.ImageUrl = @"\images\products\" + fileName + extension;
            }
            if (obj.Product.Id == 0)
            {
                _unitOfWork.Products.Add(obj.Product);
            }
            else
            {
                _unitOfWork.Products.Update(obj.Product);
            }
            _unitOfWork.Save();
            TempData["success"] = "Ürün Başarıyla Oluşturuldu";
            return RedirectToAction("Index");
        }
        return View(obj);
    }
    #region API CALLS
    [HttpGet]
    public IActionResult GetAll()
    {
        var productList = _unitOfWork.Products.GetAll(includeProperties: "ProductCategory");
        return Json(new { data = productList });
    }

    //Post
    [HttpDelete]
    public IActionResult Delete(int? id)
    {
        var obj = _unitOfWork.Products.GetFirstOrDefault(u => u.Id == id);
        if (obj == null)
        {
            return Json(new { success = false, message = "Silme Başarısız" });
        }
        var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
        if (System.IO.File.Exists(oldImagePath))
        {
            System.IO.File.Delete(oldImagePath);
        }
        _unitOfWork.Products.Remove(obj);
        _unitOfWork.Save();
        return Json(new { success = true, message = "Silme Başarılı" });
    }
    #endregion
}

StudyWeb/Views/Product/Index.cshtml
<div class="container">
    <div class="row">
        <partial name="_Index" />
    </div>
</div>

@section Scripts{
    <script src="~/js/product.js"></script>
}

StudyWeb/Views/Product/ProductCreate.cshtml
    <div class="container">
        <div class="row">
            <partial name="_ProductCreate" />
        </div>
    </div>

StudyWeb/Views/Product/Upsert.cshtml
    <div class="container">
        <div class="row">
            <partial name="_Upsert" />
        </div>
    </div>
    @section scripts
    {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
    <script>
        function ValidateInput() {
            if (document.getElementById("uploadBox").value == "") {
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'Resim Alanı Boş Bırakılamaz!',
                });
                return false;
            }
            return true;
        }
    </script>
    }

StudyWeb/Views/Product/_Index.cshtml
@model IEnumerable<Product>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Ürün Listesi</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Product" asp-action="Upsert" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Yeni Ürün Oluştur
            </a>
        </div>
    </div>
    <br /><br />
    <table id="tblData" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr class="text-center" style="border:outset">
                <th>Model</th>
                <th>Seri Numarası</th>
                <th>Imei</th>
                <th>Renk</th>
                <th>Marka</th>
                <th>Ekran Boyutu</th>
                <th>Ürün Kategorisi</th>
                <th>Fiyatı</th>
                <th>İşlem</th>
            </tr>
        </thead>
    </table>
</div>
@section Scripts{
    <script src="~/js/product.js"></script>
}

StudyWeb/Views/Product/_ProductCreate.cshtml
@model ProductCategory
<form method="post">
<div class="border p-3 mt-4">
    <div class="row pb-2">
        <h2 class="text-dark">Ürün Kategorisi Oluştur</h2> <br />
    </div>
    @*@<div asp-validation-summary="All"></div>*@ 
    <div class="mb-3">
        <label asp-for="Type" class="text-dark"></label>
        <input asp-for="Type" class="form-control" />
        <span asp-validation-for="Type" class="text-danger"></span>
    </div>
    <button type="submit" class="custom-btn btn-16" style="width:150px">Create</button>
</div>
</form>
@section scripts 
{
    @{<partial name="_ValidationScriptsPartial"></partial>}
}

StudyWeb/Views/Product/_Upsert.cshtml
@model Study.Models.ViewModels.ProductVM
<form method="post" asp-action="Upsert" enctype="multipart/form-data">
    <input asp-for="Product.Id" hidden />
    <input asp-for="Product.ImageUrl" hidden />
    <div class="row">
        <div class="col-10">
            <div class="border p-3 mt-4 row text-black">
                <div class="col-12 pb-2">
                    <h2 class="text-parimary">Ürün @(Model.Product.Id!=0?"Güncelle":"Ekle")</h2> <br />
                </div>
                @*@<div asp-validation-summary="All"></div>*@
                <div class="mb-3">
                    <label asp-for="Product.Name">Model</label>
                    <input asp-for="Product.Name" class="form-control" />
                    <span asp-validation-for="Product.Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Product.SerialNumber">Seri Numarası</label>
                    <input asp-for="Product.SerialNumber" class="form-control" />
                    <span asp-validation-for="Product.SerialNumber" class="text-danger"></span>
                </div>
                <div class="mb-3 col-6">
                    <label asp-for="Product.ImeiCode">Imei Kodu</label>
                    <input asp-for="Product.ImeiCode" class="form-control" />
                    <span asp-validation-for="Product.ImeiCode" class="text-danger"></span>
                </div>
                <div class="mb-3 col-6">
                    <label asp-for="Product.Color">Renk</label>
                    <input asp-for="Product.Color" class="form-control" />
                    <span asp-validation-for="Product.Color" class="text-danger"></span>
                </div>
                <div class="mb-3 col-6">
                    <label asp-for="Product.Mark">Marka</label>
                    <input asp-for="Product.Mark" class="form-control" />
                    <span asp-validation-for="Product.Mark" class="text-danger"></span>
                </div>
                <div class="mb-3 col-6">
                    <label asp-for="Product.Size">Ekran Boyutu</label>
                    <input asp-for="Product.Size" class="form-control" />
                    <span asp-validation-for="Product.Size" class="text-danger"></span>
                </div>
                <div class="mb-3 col-6">
                    <label asp-for="Product.Price">Fiyat</label>
                    <input asp-for="Product.Price" class="form-control" />
                    <span asp-validation-for="Product.Price" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="Product.ImageUrl"></label>
                    <input type="file" id="uploadBox" name="file" class="form-control" />                    
                </div>
                <div class="mb-3 col-6">
                    <label asp-for="Product.ProductCategoryId">Ürün Türü</label>
                    <select asp-for="Product.ProductCategoryId" asp-items="@Model.ProductCategoryList" class="form-select">
                        <option disabled selected>--Select Category--</option>
                    </select>
                    <span asp-validation-for="Product.ProductCategoryId" class="text-danger"></span>
                </div>
                <div class="col-12">
                    @if (Model.Product.Id != 0)
                    {
                        <button type="submit" onclick="return ValidateInput()" class="custom-btn btn-16" style="width:150px">Güncelle</button>
                    }
                    else
                    {
                        <button type="submit" onclick="return ValidateInput()" class="custom-btn btn-16" style="width:150px">Kaydet</button>
                    }

                    <a asp-controller="Dashboard" asp-action="Index" class="custom-btn btn-16" style="width:150px">Ana Sayfaya Geri Dön</a>
                </div>
            </div>
        </div>
        <div class="col-2">
            <img src="@Model.Product.ImageUrl" width="100%" style="border-radius:5px; border:1px solid #bbb9b9" />
        </div>
    </div>

</form>
@section scripts
    {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
    }
    @*    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'a11ychecker advcode casechange export formatpainter image editimage linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tableofcontents tinycomments tinymcespellchecker',
            toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter image editimage pageembed permanentpen table tableofcontents',
            toolbar_mode: 'floating',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
        });

    </script>*@