StudyWeb/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using Study.DataAccess.Repository.IRepository;
using Study.Models;
using Study.Models.ViewModels;
using Study.Utility;

namespace StudyWeb.Controllers
{
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public ShoppingCartVM ShoppingCartVM { get; set; }
        public int OrderTotal { get; set; }
        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        /// <summary>
        /// fasdfasfas id null sadece şu durumdaolur
        /// </summary>
        /// <params>id</params>
        /// <returns>view</returns>
        public IActionResult Index(int? id)
        {
            var sessionCartId = HttpContext.Request.Cookies["cartId"];
            Guid cartId;
            if (string.IsNullOrEmpty(sessionCartId))
            {
                cartId = Guid.NewGuid();
                HttpContext.Response.Cookies.Append("cartId", cartId.ToString());
            }
            else
            {
                cartId = Guid.Parse(sessionCartId);
            }
            ShoppingCartVM = new ShoppingCartVM()
            {
                ListCart = _unitOfWork.ShoppingCarts.GetAll(u => u.SessionGuid == cartId, includeProperties: "Product"),
                OrderHeader = new()
            };
            foreach (var cart in ShoppingCartVM.ListCart)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Price * cart.Count);
            }
            return View(ShoppingCartVM);
        }
        [HttpGet]
        public IActionResult Summary()
        {
            var sessionCartId = HttpContext.Request.Cookies["cartId"];
            Guid cartId;
            if (string.IsNullOrEmpty(sessionCartId))
            {
                cartId = Guid.NewGuid();
                HttpContext.Response.Cookies.Append("cartId", cartId.ToString(), new CookieOptions { Expires = DateTime.Now.AddDays(3) });
            }
            else
            {
                cartId = Guid.Parse(sessionCartId);
            }
            ShoppingCartVM = new ShoppingCartVM()
            {
                ListCart = _unitOfWork.ShoppingCarts.GetAll(u => u.SessionGuid == cartId, includeProperties: "Product"),
                OrderHeader = new()
            };
            foreach (var cart in ShoppingCartVM.ListCart)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Price * cart.Count);
            }
            return View(ShoppingCartVM);
        }
        [HttpPost]
        [ActionName("Summary")]
        public IActionResult SummaryPOST(ShoppingCartVM model)
        {
            var sessionCartId = HttpContext.Request.Cookies["cartId"];
            Guid cartId;
            if (string.IsNullOrEmpty(sessionCartId))
            {
                cartId = Guid.NewGuid();
                HttpContext.Response.Cookies.Append("cartId", cartId.ToString(), new CookieOptions { Expires = DateTime.Now.AddDays(3) });
            }
            else
            {
                cartId = Guid.Parse(sessionCartId);
            }
            ShoppingCartVM = new ShoppingCartVM()
            {
                ListCart = _unitOfWork.ShoppingCarts.GetAll(u => u.SessionGuid == cartId, includeProperties: "Product"),
                OrderHeader = new()
            };
            ShoppingCartVM.OrderHeader = model.OrderHeader;
            foreach (var cart in ShoppingCartVM.ListCart)
            {
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Price * cart.Count);
            }
            _unitOfWork.OrderHeaders.Add(ShoppingCartVM.OrderHeader);
            _unitOfWork.Save();
            foreach (var cart in ShoppingCartVM.ListCart)
            {
                OrderDetail orderDetail = new()
                {
                    ProductId = cart.ProductId,
                    OrderId = ShoppingCartVM.OrderHeader.Id,
                    Price = cart.Price,
                    Count = cart.Count
                };
                _unitOfWork.OrderDetails.Add(orderDetail);
                _unitOfWork.Save();
            }
            //stripe ayarları
            var domain = "https://localhost:44354/";
            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string>
                {
                    "card",
                },
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
                SuccessUrl = domain + $"Cart/OrderConfirmation?id={ShoppingCartVM.OrderHeader.Id}",
                CancelUrl = domain + $"Cart/Index",
            };
            foreach (var item in ShoppingCartVM.ListCart)
            {
                var sessionLineItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.Price * 100),
                        Currency = "try",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product.Name
                        },
                    },
                    Quantity = item.Count,
                };
                options.LineItems.Add(sessionLineItem);
            }
            var service = new SessionService();
            Session session = service.Create(options);
            _unitOfWork.OrderHeaders.UpdateStripePaymentId(ShoppingCartVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
            _unitOfWork.Save();
            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }

        public IActionResult OrderConfirmation(int id)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeaders.GetFirstOrDefault(u => u.Id == id);
            //OrderDetail orderDetail = _unitOfWork.OrderDetails.GetFirstOrDefault(u => u.Id == id);
            if (orderHeader.PaymentStatus != SD.PaymentStatusDelayedPayment)
            {
                var service = new SessionService();
                Session session = service.Get(orderHeader.SessionId);
                //check the stripe status
                if (session.PaymentStatus.ToLower() == "paid")
                {
                    _unitOfWork.OrderHeaders.UpdateStatus(id, SD.StatusApproved, SD.PaymentStatusApproved);
                    _unitOfWork.Save();
                }
            }
            ViewBag.OrderTotal = orderHeader.OrderTotal;
            List<ShoppingCart> shoppingCarts = _unitOfWork.ShoppingCarts.GetAll(u => u.Id == id).ToList();
            HttpContext.Session.Clear();
            HttpContext.Response.Cookies.Delete("cartId");
            _unitOfWork.ShoppingCarts.RemoveRange(shoppingCarts);
            _unitOfWork.Save();
            return View(id);
        }

        public IActionResult Plus(int cartId)
        {
            var sessionCartId = HttpContext.Request.Cookies["cartId"];
            Guid cartGuidId;
            if (string.IsNullOrEmpty(sessionCartId))
            {
                cartGuidId = Guid.NewGuid();
                HttpContext.Response.Cookies.Append("cartId", cartGuidId.ToString());
            }
            else
            {
                cartGuidId = Guid.Parse(sessionCartId);
            }
            var cart = _unitOfWork.ShoppingCarts.GetFirstOrDefault(u => u.SessionGuid == cartGuidId && u.Id == cartId);
            _unitOfWork.ShoppingCarts.IncrementCount(cart, 1);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Minus(int cartId)
        {
            var sessionCartId = HttpContext.Request.Cookies["cartId"];
            Guid cartGuidId;
            if (string.IsNullOrEmpty(sessionCartId))
            {
                cartGuidId = Guid.NewGuid();
                HttpContext.Response.Cookies.Append("cartId", cartGuidId.ToString());
            }
            else
            {
                cartGuidId = Guid.Parse(sessionCartId);
            }
            var cart = _unitOfWork.ShoppingCarts.GetFirstOrDefault(u => u.Id == cartId);
            if (cart.Count <= 1)
            {
                _unitOfWork.ShoppingCarts.Remove(cart);
                TempData["success"] = "Ürün Silindi";
                var count = _unitOfWork.ShoppingCarts.GetAll(u => u.SessionGuid == cartGuidId && u.Id == cartId).ToList().Count - 1;
                HttpContext.Session.SetInt32(SD.SessionCart, count);
            }
            else
            {
                _unitOfWork.ShoppingCarts.DecrementCount(cart, 1);
            }
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Remove(int cartId)
        {
            var sessionCartId = HttpContext.Request.Cookies["cartId"];
            Guid cartGuidId;
            if (string.IsNullOrEmpty(sessionCartId))
            {
                cartGuidId = Guid.NewGuid();
                HttpContext.Response.Cookies.Append("cartId", cartGuidId.ToString());
            }
            else
            {
                cartGuidId = Guid.Parse(sessionCartId);
            }
            var cart = _unitOfWork.ShoppingCarts.GetFirstOrDefault(u => u.Id == cartId);
            _unitOfWork.ShoppingCarts.Remove(cart);
            _unitOfWork.Save();
            var count = _unitOfWork.ShoppingCarts.GetAll(u => u.SessionGuid == cartGuidId && u.Id == cartId).ToList().Count;
            HttpContext.Session.SetInt32(SD.SessionCart, count);
            TempData["success"] = "Ürün Silindi!";
            return RedirectToAction(nameof(Index));
        }
    }
}

StudyWeb/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Study.DataAccess.Repository.IRepository;
using Study.Models;

namespace StudyWeb.Controllers
{

    public class DashboardController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public DashboardController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ProductCategoryList()
        {
            IEnumerable<ProductCategory> objProductCategoryList = _unitOfWork.ProductCategory.GetAll();
            return View(objProductCategoryList);
        }
        public IActionResult ProductCategoryCreate()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ProductCategoryCreate(ProductCategory obj)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.ProductCategory.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Ürün kategorisi oluşturuldu";
                return RedirectToAction("ProductCategoryList");
            }
            return View(obj);
        }
        public IActionResult ProductCategoryDelete(int? id)
        {
            IEnumerable<ProductCategory> objProductCategoryList = _unitOfWork.ProductCategory.GetAll();
            return View(objProductCategoryList);
        }        
       // [HttpPost]
       // [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.ProductCategory.GetFirstOrDefault(u => u.Id == id);
            if(obj==null)
            {
                return NotFound();
            }
            _unitOfWork.ProductCategory.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "Ürün Kategorisi Başarıyla Silindi";
            return RedirectToAction("ProductCategoryDelete");
        }

        //Get
        public IActionResult ProductCategoryUpdate()
        {
            IEnumerable<ProductCategory> objProductCategoryList = _unitOfWork.ProductCategory.GetAll();
            return View(objProductCategoryList);
        }
        public IActionResult ProductCategoryUpdated(int? id)
        {
            if (id==null || id==0)
            {
                return NotFound();
            }
            var ProductCategoryFromDbFirst = _unitOfWork.ProductCategory.GetFirstOrDefault(u => u.Id == id);
            if(ProductCategoryFromDbFirst==null)
            {
                return NotFound();
            }
            return View(ProductCategoryFromDbFirst);
        }
        //POST
        [HttpPost]
        public IActionResult ProductCategoryUpdated(ProductCategory obj)
        {
            if(ModelState.IsValid)
            {
                _unitOfWork.ProductCategory.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Ürün Kategorisi Düzenleme Başarılı";
                return RedirectToAction("ProductCategoryList");
            }
            return View(obj);
        }
        public IActionResult ProductCreate()
        {
            return View();
        }

    }
}

StudyWeb/ViewComponents/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Study.DataAccess.Repository.IRepository;
using Study.Models;
using Study.Utility;

namespace StudyWeb.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var sessionCartId = HttpContext.Request.Cookies["cartId"];
            Guid cartId;
            if (string.IsNullOrEmpty(sessionCartId))
            {
                cartId = Guid.NewGuid();
                HttpContext.Response.Cookies.Append("cartId", cartId.ToString(), new CookieOptions { Expires = DateTime.Now.AddDays(3) });
            }
            else
            {
                cartId = Guid.Parse(sessionCartId);
            }


            if (HttpContext.Session.GetInt32(SD.SessionCart) != null)
            {
                return View(HttpContext.Session.GetInt32(SD.SessionCart));
            }
            else
            {
                HttpContext.Session.SetInt32(SD.SessionCart, _unitOfWork.ShoppingCarts.GetAll(u => u.SessionGuid == cartId).ToList().Count);
                return View(HttpContext.Session.GetInt32(SD.SessionCart));
            }
        }
    }
}

StudyWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudyWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudyWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Product.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="~/css/horizontalmedia.css">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/product/">
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha512-EKWWs1ZcA2ZY9lbLISPz8aGR2+L7JVYqBAYTq5AXgBkSjRSuQEGqWx8R1zAX16KdXPaCjOCaKE8MCpU0wcHlHA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script nomodule>window.MSInputMethodContext && document.documentMode && document.write('<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-ie11@5/css/bootstrap-ie11.min.css"><script src="https://cdn.jsdelivr.net/npm/ie11-custom-properties@4/ie11CustomProperties.min.js"><\/script>');</script>
    <link rel="stylesheet" href="~/css/dark-mode.css">
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2280%22>🌓</text></svg>" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5/dist/css/bootstrap.min.css" />
</head>
<body>
    <header class="site-header sticky-top py-1">
        <nav class="container d-flex flex-column flex-md-row justify-content-between">
            <a class="py-2" asp-controller="Home" asp-action="Index" aria-label="Product">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mx-auto" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10" /><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94" /></svg>
            </a>
            <a class="py-2 d-none d-md-inline-block" asp-controller="Home" asp-action="ProductFiltre" asp-route-id="telefon">Telefon</a>
            <a class="py-2 d-none d-md-inline-block" asp-controller="Home" asp-action="ProductFiltre" asp-route-id="tablet">Tablet</a>
            <a class="py-2 d-none d-md-inline-block" asp-controller="Home" asp-action="ProductFiltre" asp-route-id="laptop">Laptop</a>
            <a class="py-2 d-none d-md-inline-block" asp-controller="Home" asp-action="ProductFiltre" asp-route-id="monitor">Monitör</a>
            &nbsp;&nbsp;&nbsp;
            <a class="py-2 d-none d-md-inline-block nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Hakkımızda</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" asp-controller="Home" asp-action="Contactus">İletişim</a>
                <a class="dropdown-item" asp-controller="Home" asp-action="Aboutus">Biz Kimiz?</a>
            </div>
            <a class="py-2 d-none d-md-inline-block" asp-controller="Dashboard" asp-action="Index">Yönetim</a>
            <a class="py-2 d-none d-md-inline-block" asp-controller="LoginSign" asp-action="Index">Giriş Yap/Kayıt Ol</a>
            <a class="py-2 d-none d-md-inline-block" asp-controller="Cart" asp-action="Index">@await Component.InvokeAsync("ShoppingCart")</a>
            <a> <div class="nav-link">

                <div class="form-check form-switch">
                    <input type="checkbox" class="form-check-input" id="darkSwitch">
                    <label class="custom-control-label" for="darkSwitch">Dark Mode</label>
                </div>
                <script src="~/js/dark-mode-switch.min.js"></script>
            </div></a>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer  py-5" style="background-color:#d9d9d98f">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="d-block mb-2" role="img" viewBox="0 0 24 24"><title>Product</title><circle cx="12" cy="12" r="10" /><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94" /></svg>
                    <span class="d-block mb-3 text-muted">&copy; 2022</span>
                </div>
                <div class="col-6 col-md">
                    <h5><a asp-controller="Home" asp-action="ProductFiltre" asp-route-id="telefon">Telefon</a></h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="link-secondary" asp-controller="Home" asp-action="ProductFiltre" asp-route-id="telefon_samsung">Samsung</a></li>
                        <li><a class="link-secondary" href="#">Xiaomi</a></li>
                        <li><a class="link-secondary" asp-controller="Home" asp-action="ProductFiltre" asp-route-id="telefon_apple">Apple</a></li>
                        <li><a class="link-secondary" href="#">Oppo</a></li>
                        <li><a class="link-secondary" href="#">Huawei</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5><a asp-controller="Home" asp-action="ProductFiltre" asp-route-id="tablet">Tablet</a></h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="link-secondary" asp-controller="Home" asp-action="ProductFiltre" asp-route-id="tablet_samsung">Samsung</a></li>
                        <li><a class="link-secondary" asp-controller="Home" asp-action="ProductFiltre" asp-route-id="tablet_apple">Apple</a></li>
                        <li><a class="link-secondary" href="#">Huawei</a></li>
                        <li><a class="link-secondary" href="#">Diğer</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5><a asp-controller="Home" asp-action="ProductFiltre" asp-route-id="monitor">Monitör</a></h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="link-secondary" href="#">Msi</a></li>
                        <li><a class="link-secondary" href="#">Asus</a></li>
                        <li><a class="link-secondary" href="#">Lg</a></li>
                        <li><a class="link-secondary" href="#">Viewsonic</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5><a asp-controller="Home" asp-action="ProductFiltre" asp-route-id="laptop">Laptop</a></h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="link-secondary" href="#">Msi</a></li>
                        <li><a class="link-secondary" asp-controller="Home" asp-action="ProductFiltre" asp-route-id="laptop_asus">Asus</a></li>
                        <li><a class="link-secondary" href="#">Dell</a></li>
                        <li><a class="link-secondary" href="#">Acer</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5><a href="@Url.Action("Aboutus","Home")">Hakkımızda</a></h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="link-secondary" href="#">Şirket</a></li>
                        <li><a class="link-secondary" href="#">Biz Kimiz?</a></li>
                        <li><a class="link-secondary" asp-controller="Home" asp-action="Contactus">İletişim</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js" integrity="sha512-6PM0qYu5KExuNcKt5bURAoT6KCThUmHRewN3zUFNaoI6Di7XJPTMoT6K0nsagZKk2OB4L7E3q1uQKHNHd4stIQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js   " integrity="sha512-sH8JPhKJUeA9PWk3eOcOl8U+lfZTgtBXD41q6cO/slwxGHCxKcW45K4oPCUhHG7NMB4mbKEddVmPuTXtpbCbFA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StudyWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"]!=null)
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}
@if(TempData["error"]!=null)
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["success"]')
    </script>
}